# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a5e5b9116e205f7dac0565459177f8dda0c977a5ec5025f6a893aa780680bfb7868acb659917faf60f5c5f8c02338d0b5586d4ca0c25737e02f0d1b864a4d238

test:
  secret_key_base: b2c5bf4aa2607fc57f3454626cf68f1d9c7c9ae7fc43ce550caeb2d0b296e0fdaf0f8152f0c1481a5d9833051de9b2c03e4af6a39b7daa5e8f0a252fabdb8d28

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
